options:
  logging: GCS_ONLY
  logsBucket: 'gs://thotaterra/build-logs'
  service_account: 'terraformfordevlopment@vaulted-epigram-457004-c6.iam.gserviceaccount.com'

steps:
  - name: hashicorp/terraform:1.5.7
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        terraform init \
          -backend-config="bucket=thotaterra" \
          -backend-config="prefix=terraform/state"

  - name: hashicorp/terraform:1.5.7
    id: Terraform Plan
    entrypoint: sh
    args:
      - -
