options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/vaulted-epigram-457004-c6/secrets/service-account-key/versions/latest
      env: 'SERVICE_ACCOUNT_KEY'

serviceAccount: 'terraformfordevlopment@vaulted-epigram-457004-c6.iam.gserviceaccount.com'

steps:
  - name: hashicorp/terraform:1.5.7
    id: Terraform Init
    entrypoint: sh
    secretEnv: ['SERVICE_ACCOUNT_KEY']
    args:
      - -c
      - |
        echo "$$SERVICE_ACCOUNT_KEY" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        terraform init \
          -backend-config="bucket=thotaterra" \
          -backend-config="prefix=terraform/state" \
          -reconfigure

  - name: hashicorp/terraform:1.5.7
    id: Terraform Plan
    entrypoint: sh
    secretEnv: ['SERVICE_ACCOUNT_KEY']
    args:
      - -c
      - |
        echo "$$SERVICE_ACCOUNT_KEY" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        terraform plan -out=plan.tfplan -var-file="terraform.tfvars"
        terraform show -no-color plan.tfplan > tfplan.txt

  - name: gcr.io/cloud-builders/gcloud
    id: Approval
    waitFor: ['Terraform Plan']
    args:
      - beta
      - builds
      - wait-for-approval

  - name: hashicorp/terraform:1.5.7
    id: Terraform Apply
    waitFor: ['Approval']
    entrypoint: sh
    secretEnv: ['SERVICE_ACCOUNT_KEY']
    args:
      - -c
      - |
        echo "$$SERVICE_ACCOUNT_KEY" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        terraform apply -auto-approve plan.tfplan

  - name: hashicorp/terraform:1.5.7
    id: Terraform Output
    waitFor: ['Terraform Apply']
    entrypoint: sh
    secretEnv: ['SERVICE_ACCOUNT_KEY']
    args:
      - -c
      - |
        echo "$$SERVICE_ACCOUNT_KEY" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        terraform output
