options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/vaulted-epigram-457004-c6/secrets/service-account-key/versions/latest
    env: 'SERVICE_ACCOUNT_KEY'

serviceAccount: 'terraformfordevlopment@vaulted-epigram-457004-c6.iam.gserviceaccount.com'

steps:
  - name: hashicorp/terraform:1.5.7
    id: Write Service Account Key and Run Terraform
    entrypoint: sh
    args:
      - -c
      - |
         terraform init \
          -backend-config="bucket=thotaterra" \
          -backend-config="prefix=terraform/state"
        terraform plan -var-file="terraform.tfvars"
    secretEnv: ['SERVICE_ACCOUNT_KEY']
