steps:
  - name: 'hashicorp/terraform:1.5.7'
    id: Terraform Init & Plan
    entrypoint: sh
    secretEnv: ['SERVICE_ACCOUNT_KEY']
    args:
      - -c
      - |
        echo "$$SERVICE_ACCOUNT_KEY" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=key.json
        terraform init \
          -backend-config="bucket=thotaterra" \
          -backend-config="prefix=terraform/state" \
          -reconfigure
        terraform plan -out=tfplan
        terraform show -no-color tfplan > plan_output.txt
        cat plan_output.txt

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Upload Plan Output
    args: ['cp', 'plan_output.txt', 'gs://thotaterra/plans/plan_output.txt']

  - name: 'hashicorp/terraform:1.5.7'
    id: Terraform Apply
    waitFor: ['-']
    entrypoint: sh
    secretEnv: ['SERVICE_ACCOUNT_KEY']
    args:
      - -c
      - |
        echo "$$SERVICE_ACCOUNT_KEY" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=key.json
        terraform apply -auto-approve tfplan

availableSecrets:
  secretManager:
    - versionName: projects/vaulted-epigram-457004-c6/secrets/service-account-key/versions/latest
      env: 'SERVICE_ACCOUNT_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
