options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: '932539802604-compute@developer.gserviceaccount.com'

availableSecrets:
  secretManager:
    - versionName: projects/932539802604/secrets/service-account-key/versions/latest
      env: 'SERVICE_ACCOUNT_KEY'

steps:
  - name: hashicorp/terraform:1.5.7
    id: Terraform Init
    entrypoint: sh
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/credentials.json'
    volumes:
      - name: 'credentials'
        secret:
          secretManager:
            versionName: projects/932539802604/secrets/service-account-key/versions/latest
    args:
      - -c
      - |
        cp /credentials/service-account-key /workspace/credentials.json
        terraform init \
          -backend-config="bucket=thotaterra" \
          -backend-config="
