options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/vaulted-epigram-457004-c6/secrets/service-account-key/versions/latest
    env: 'SERVICE_ACCOUNT_KEY'

serviceAccount: 'terraformfordevlopment@vaulted-epigram-457004-c6.iam.gserviceaccount.com'

steps:
  - name: hashicorp/terraform:1.5.7
    id: Write Service Account Key
    entrypoint: sh
    args:
      - -c
      - |
        cat /secrets/service-account-key/key.json > /workspace/key.json
    volumes:
    - name: service-account-key
      path: /secrets/service-account-key

  - name: hashicorp/terraform:1.5.7
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        terraform init \
          -backend-config="bucket=thotaterra" \
          -backend-config="prefix=terraform/state"

  - name: hashicorp/terraform:1.5.7
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        terraform plan -var-file="terraform.tfvars"
