steps:
  # Your build steps here

options:
  serviceAccount: '932539802604-compute@developer.gserviceaccount.com'
steps:
  - name: hashicorp/terraform:1.5.7
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        terraform init \
          -backend-config="bucket=thotaterra" \
          -backend-config="prefix=terraform/state"

  - name: hashicorp/terraform:1.5.7
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan -var-file="terraform.tfvars"
