- name: gcr.io/cloud-builders/curl
  args: ["https://registry.terraform.io"]
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/vaulted-epigram-457004-c6/secrets/service-account-key/versions/latest
    env: 'SERVICE_ACCOUNT_KEY'

serviceAccount: 'terraformfordevlopment@vaulted-epigram-457004-c6.iam.gserviceaccount.com'

steps:
  - name: hashicorp/terraform:1.5.7
    id: Write Service Account Key and Run Terraform
    entrypoint: sh
    args:
      - -c
      - |
        echo "Writing service account key to file..."
        echo $$SERVICE_ACCOUNT_KEY > key.json
        echo "Service account key written to file."
        cat key.json
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        echo "Initializing Terraform..."
        terraform init \
          -backend-config="bucket=thotaterra" \
          -backend-config="prefix=terraform/state" \
          -reconfigure
        echo "Running Terraform plan..."
        terraform plan -var-file="terraform.tfvars"
    secretEnv: ['SERVICE_ACCOUNT_KEY']
