options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/your-project-id/secrets/service-account-key/versions/latest
      env: SERVICE_ACCOUNT_KEY

serviceAccount: 'your-service-account@your-project-id.iam.gserviceaccount.com'

steps:
  # Step 0: Authenticate
  - name: gcr.io/cloud-builders/gcloud
    id: Setup Auth
    entrypoint: sh
    secretEnv: [SERVICE_ACCOUNT_KEY]
    args:
      - -c
      - |
        echo "$$SERVICE_ACCOUNT_KEY" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json

  # Step 1: Terraform Init
  - name: hashicorp/terraform:1.5.7
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        terraform init -backend-config="bucket=thotaterra" -backend-config="prefix=terraform/state" -reconfigure

  # Step 2: Terraform Plan
  - name: hashicorp/terraform:1.5.7
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        terraform plan -var-file="terraform.tfvars" > terraform_plan_output.txt

  # Step 3: Upload Plan Output to GCS
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Upload Plan Output
    entrypoint: sh
    args:
      - -c
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        gsutil cp terraform_plan_output.txt gs://thotaterra/terraform-plans/terraform_plan_output-${BUILD_ID}.txt

  # Step 4: Terraform Apply (waits for manual approval)
  - name: hashicorp/terraform:1.5.7
    id: Terraform Apply
    approvalRequired: true  # 🛑 Requires Manual Approval!
    entrypoint: sh
    args:
      - -c
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        terraform apply -var-file="terraform.tfvars" -auto-approve

  # Step 5: Terraform Output
  - name: hashicorp/terraform:1.5.7
    id: Terraform Output
    entrypoint: sh
    args:
      - -c
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json
        terraform output
